import json
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors


def generate_pdf(
    certificate_file="forensic_certificate.json",
    output_file="forensic_certificate.pdf"
):
    folder = Path(__file__).parent

    certificate_path = folder / certificate_file
    pdf_path = folder / output_file

    with open(
        certificate_path,
        "r",
        encoding="utf-8"
    ) as file:
        certificate = json.load(file)

    styles = getSampleStyleSheet()

    document = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4
    )

    content = []

    content.append(
        Paragraph(
            "Voice Clone Forensic Certificate",
            styles["Title"]
        )
    )

    content.append(Spacer(1, 20))

    summary_data = [
        ["Certificate Type", certificate["certificate_type"]],
        ["Generated At", certificate["generated_at"]],
        ["Chain Length", str(certificate["chain_length"])],
        ["Final Hash", certificate["final_hash"]],
    ]

    summary_table = Table(summary_data, colWidths=[150, 350])

    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("WORDWRAP", (0, 0), (-1, -1), True),
        ])
    )

    content.append(summary_table)
    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Forensic Chain Records",
            styles["Heading2"]
        )
    )

    chain_data = [
        [
            "Frame",
            "Timestamp",
            "Risk Score",
            "Risk Tier",
            "Audio Hash"
        ]
    ]

    for entry in certificate["chain"]:
        chain_data.append([
            str(entry["frame_index"]),
            entry["timestamp"],
            str(entry["score"]),
            entry["risk_tier"],
            entry["audio_sha256"]
        ])

    chain_table = Table(
        chain_data,
        colWidths=[40, 120, 65, 75, 180],
        repeatRows=1
    )

    chain_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
            ("FONTSIZE", (0, 0), (-1, -1), 7),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ])
    )

    content.append(chain_table)
    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Certificate generated by the Beyond404 forensic module.",
            styles["Normal"]
        )
    )

    document.build(content)

    return pdf_path


if __name__ == "__main__":
    output = generate_pdf()
    print("PDF certificate generated successfully:")
    print(output)